/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedForestRouteImport } from './routes/_authenticated/forest'
import { Route as AuthenticatedFriendsIndexRouteImport } from './routes/_authenticated/friends.index'
import { Route as AuthenticatedForestIndexRouteImport } from './routes/_authenticated/forest.index'
import { Route as AuthenticatedHabitsNewRouteImport } from './routes/_authenticated/habits.new'
import { Route as AuthenticatedHabitsHabitIdRouteImport } from './routes/_authenticated/habits.$habitId'
import { Route as AuthenticatedFriendsAddRouteImport } from './routes/_authenticated/friends.add'
import { Route as AuthenticatedForestOwnerIdRouteImport } from './routes/_authenticated/forest.$ownerId'
import { Route as AuthenticatedHabitsHabitIdEditRouteImport } from './routes/_authenticated/habits.$habitId.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForestRoute = AuthenticatedForestRouteImport.update({
  id: '/forest',
  path: '/forest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsIndexRoute =
  AuthenticatedFriendsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFriendsRoute,
  } as any)
const AuthenticatedForestIndexRoute =
  AuthenticatedForestIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedForestRoute,
  } as any)
const AuthenticatedHabitsNewRoute = AuthenticatedHabitsNewRouteImport.update({
  id: '/habits/new',
  path: '/habits/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsHabitIdRoute =
  AuthenticatedHabitsHabitIdRouteImport.update({
    id: '/habits/$habitId',
    path: '/habits/$habitId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFriendsAddRoute = AuthenticatedFriendsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedFriendsRoute,
} as any)
const AuthenticatedForestOwnerIdRoute =
  AuthenticatedForestOwnerIdRouteImport.update({
    id: '/$ownerId',
    path: '/$ownerId',
    getParentRoute: () => AuthenticatedForestRoute,
  } as any)
const AuthenticatedHabitsHabitIdEditRoute =
  AuthenticatedHabitsHabitIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedHabitsHabitIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forest': typeof AuthenticatedForestRouteWithChildren
  '/friends': typeof AuthenticatedFriendsRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/forest/$ownerId': typeof AuthenticatedForestOwnerIdRoute
  '/friends/add': typeof AuthenticatedFriendsAddRoute
  '/habits/$habitId': typeof AuthenticatedHabitsHabitIdRouteWithChildren
  '/habits/new': typeof AuthenticatedHabitsNewRoute
  '/forest/': typeof AuthenticatedForestIndexRoute
  '/friends/': typeof AuthenticatedFriendsIndexRoute
  '/habits/$habitId/edit': typeof AuthenticatedHabitsHabitIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/forest/$ownerId': typeof AuthenticatedForestOwnerIdRoute
  '/friends/add': typeof AuthenticatedFriendsAddRoute
  '/habits/$habitId': typeof AuthenticatedHabitsHabitIdRouteWithChildren
  '/habits/new': typeof AuthenticatedHabitsNewRoute
  '/forest': typeof AuthenticatedForestIndexRoute
  '/friends': typeof AuthenticatedFriendsIndexRoute
  '/habits/$habitId/edit': typeof AuthenticatedHabitsHabitIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/forest': typeof AuthenticatedForestRouteWithChildren
  '/_authenticated/friends': typeof AuthenticatedFriendsRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/forest/$ownerId': typeof AuthenticatedForestOwnerIdRoute
  '/_authenticated/friends/add': typeof AuthenticatedFriendsAddRoute
  '/_authenticated/habits/$habitId': typeof AuthenticatedHabitsHabitIdRouteWithChildren
  '/_authenticated/habits/new': typeof AuthenticatedHabitsNewRoute
  '/_authenticated/forest/': typeof AuthenticatedForestIndexRoute
  '/_authenticated/friends/': typeof AuthenticatedFriendsIndexRoute
  '/_authenticated/habits/$habitId/edit': typeof AuthenticatedHabitsHabitIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forest'
    | '/friends'
    | '/history'
    | '/onboarding'
    | '/settings'
    | '/today'
    | '/forest/$ownerId'
    | '/friends/add'
    | '/habits/$habitId'
    | '/habits/new'
    | '/forest/'
    | '/friends/'
    | '/habits/$habitId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/onboarding'
    | '/settings'
    | '/today'
    | '/forest/$ownerId'
    | '/friends/add'
    | '/habits/$habitId'
    | '/habits/new'
    | '/forest'
    | '/friends'
    | '/habits/$habitId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/forest'
    | '/_authenticated/friends'
    | '/_authenticated/history'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/today'
    | '/_authenticated/forest/$ownerId'
    | '/_authenticated/friends/add'
    | '/_authenticated/habits/$habitId'
    | '/_authenticated/habits/new'
    | '/_authenticated/forest/'
    | '/_authenticated/friends/'
    | '/_authenticated/habits/$habitId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forest': {
      id: '/_authenticated/forest'
      path: '/forest'
      fullPath: '/forest'
      preLoaderRoute: typeof AuthenticatedForestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends/': {
      id: '/_authenticated/friends/'
      path: '/'
      fullPath: '/friends/'
      preLoaderRoute: typeof AuthenticatedFriendsIndexRouteImport
      parentRoute: typeof AuthenticatedFriendsRoute
    }
    '/_authenticated/forest/': {
      id: '/_authenticated/forest/'
      path: '/'
      fullPath: '/forest/'
      preLoaderRoute: typeof AuthenticatedForestIndexRouteImport
      parentRoute: typeof AuthenticatedForestRoute
    }
    '/_authenticated/habits/new': {
      id: '/_authenticated/habits/new'
      path: '/habits/new'
      fullPath: '/habits/new'
      preLoaderRoute: typeof AuthenticatedHabitsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits/$habitId': {
      id: '/_authenticated/habits/$habitId'
      path: '/habits/$habitId'
      fullPath: '/habits/$habitId'
      preLoaderRoute: typeof AuthenticatedHabitsHabitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends/add': {
      id: '/_authenticated/friends/add'
      path: '/add'
      fullPath: '/friends/add'
      preLoaderRoute: typeof AuthenticatedFriendsAddRouteImport
      parentRoute: typeof AuthenticatedFriendsRoute
    }
    '/_authenticated/forest/$ownerId': {
      id: '/_authenticated/forest/$ownerId'
      path: '/$ownerId'
      fullPath: '/forest/$ownerId'
      preLoaderRoute: typeof AuthenticatedForestOwnerIdRouteImport
      parentRoute: typeof AuthenticatedForestRoute
    }
    '/_authenticated/habits/$habitId/edit': {
      id: '/_authenticated/habits/$habitId/edit'
      path: '/edit'
      fullPath: '/habits/$habitId/edit'
      preLoaderRoute: typeof AuthenticatedHabitsHabitIdEditRouteImport
      parentRoute: typeof AuthenticatedHabitsHabitIdRoute
    }
  }
}

interface AuthenticatedForestRouteChildren {
  AuthenticatedForestOwnerIdRoute: typeof AuthenticatedForestOwnerIdRoute
  AuthenticatedForestIndexRoute: typeof AuthenticatedForestIndexRoute
}

const AuthenticatedForestRouteChildren: AuthenticatedForestRouteChildren = {
  AuthenticatedForestOwnerIdRoute: AuthenticatedForestOwnerIdRoute,
  AuthenticatedForestIndexRoute: AuthenticatedForestIndexRoute,
}

const AuthenticatedForestRouteWithChildren =
  AuthenticatedForestRoute._addFileChildren(AuthenticatedForestRouteChildren)

interface AuthenticatedFriendsRouteChildren {
  AuthenticatedFriendsAddRoute: typeof AuthenticatedFriendsAddRoute
  AuthenticatedFriendsIndexRoute: typeof AuthenticatedFriendsIndexRoute
}

const AuthenticatedFriendsRouteChildren: AuthenticatedFriendsRouteChildren = {
  AuthenticatedFriendsAddRoute: AuthenticatedFriendsAddRoute,
  AuthenticatedFriendsIndexRoute: AuthenticatedFriendsIndexRoute,
}

const AuthenticatedFriendsRouteWithChildren =
  AuthenticatedFriendsRoute._addFileChildren(AuthenticatedFriendsRouteChildren)

interface AuthenticatedHabitsHabitIdRouteChildren {
  AuthenticatedHabitsHabitIdEditRoute: typeof AuthenticatedHabitsHabitIdEditRoute
}

const AuthenticatedHabitsHabitIdRouteChildren: AuthenticatedHabitsHabitIdRouteChildren =
  {
    AuthenticatedHabitsHabitIdEditRoute: AuthenticatedHabitsHabitIdEditRoute,
  }

const AuthenticatedHabitsHabitIdRouteWithChildren =
  AuthenticatedHabitsHabitIdRoute._addFileChildren(
    AuthenticatedHabitsHabitIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedForestRoute: typeof AuthenticatedForestRouteWithChildren
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedHabitsHabitIdRoute: typeof AuthenticatedHabitsHabitIdRouteWithChildren
  AuthenticatedHabitsNewRoute: typeof AuthenticatedHabitsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedForestRoute: AuthenticatedForestRouteWithChildren,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedHabitsHabitIdRoute: AuthenticatedHabitsHabitIdRouteWithChildren,
  AuthenticatedHabitsNewRoute: AuthenticatedHabitsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
