/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedYouRouteImport } from './routes/_authenticated/you'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedForestRouteImport } from './routes/_authenticated/forest'
import { Route as AuthenticatedHabitsNewRouteImport } from './routes/_authenticated/habits.new'
import { Route as AuthenticatedHabitsHabitIdRouteImport } from './routes/_authenticated/habits.$habitId'
import { Route as AuthenticatedHabitsHabitIdEditRouteImport } from './routes/_authenticated/habits.$habitId.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYouRoute = AuthenticatedYouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForestRoute = AuthenticatedForestRouteImport.update({
  id: '/forest',
  path: '/forest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsNewRoute = AuthenticatedHabitsNewRouteImport.update({
  id: '/habits/new',
  path: '/habits/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsHabitIdRoute =
  AuthenticatedHabitsHabitIdRouteImport.update({
    id: '/habits/$habitId',
    path: '/habits/$habitId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHabitsHabitIdEditRoute =
  AuthenticatedHabitsHabitIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedHabitsHabitIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/forest': typeof AuthenticatedForestRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/you': typeof AuthenticatedYouRoute
  '/habits/$habitId': typeof AuthenticatedHabitsHabitIdRouteWithChildren
  '/habits/new': typeof AuthenticatedHabitsNewRoute
  '/habits/$habitId/edit': typeof AuthenticatedHabitsHabitIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/forest': typeof AuthenticatedForestRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/you': typeof AuthenticatedYouRoute
  '/habits/$habitId': typeof AuthenticatedHabitsHabitIdRouteWithChildren
  '/habits/new': typeof AuthenticatedHabitsNewRoute
  '/habits/$habitId/edit': typeof AuthenticatedHabitsHabitIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/forest': typeof AuthenticatedForestRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/you': typeof AuthenticatedYouRoute
  '/_authenticated/habits/$habitId': typeof AuthenticatedHabitsHabitIdRouteWithChildren
  '/_authenticated/habits/new': typeof AuthenticatedHabitsNewRoute
  '/_authenticated/habits/$habitId/edit': typeof AuthenticatedHabitsHabitIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/forest'
    | '/friends'
    | '/onboarding'
    | '/settings'
    | '/today'
    | '/you'
    | '/habits/$habitId'
    | '/habits/new'
    | '/habits/$habitId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/forest'
    | '/friends'
    | '/onboarding'
    | '/settings'
    | '/today'
    | '/you'
    | '/habits/$habitId'
    | '/habits/new'
    | '/habits/$habitId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/forest'
    | '/_authenticated/friends'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/today'
    | '/_authenticated/you'
    | '/_authenticated/habits/$habitId'
    | '/_authenticated/habits/new'
    | '/_authenticated/habits/$habitId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/you': {
      id: '/_authenticated/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof AuthenticatedYouRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forest': {
      id: '/_authenticated/forest'
      path: '/forest'
      fullPath: '/forest'
      preLoaderRoute: typeof AuthenticatedForestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits/new': {
      id: '/_authenticated/habits/new'
      path: '/habits/new'
      fullPath: '/habits/new'
      preLoaderRoute: typeof AuthenticatedHabitsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits/$habitId': {
      id: '/_authenticated/habits/$habitId'
      path: '/habits/$habitId'
      fullPath: '/habits/$habitId'
      preLoaderRoute: typeof AuthenticatedHabitsHabitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits/$habitId/edit': {
      id: '/_authenticated/habits/$habitId/edit'
      path: '/edit'
      fullPath: '/habits/$habitId/edit'
      preLoaderRoute: typeof AuthenticatedHabitsHabitIdEditRouteImport
      parentRoute: typeof AuthenticatedHabitsHabitIdRoute
    }
  }
}

interface AuthenticatedHabitsHabitIdRouteChildren {
  AuthenticatedHabitsHabitIdEditRoute: typeof AuthenticatedHabitsHabitIdEditRoute
}

const AuthenticatedHabitsHabitIdRouteChildren: AuthenticatedHabitsHabitIdRouteChildren =
  {
    AuthenticatedHabitsHabitIdEditRoute: AuthenticatedHabitsHabitIdEditRoute,
  }

const AuthenticatedHabitsHabitIdRouteWithChildren =
  AuthenticatedHabitsHabitIdRoute._addFileChildren(
    AuthenticatedHabitsHabitIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedForestRoute: typeof AuthenticatedForestRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedYouRoute: typeof AuthenticatedYouRoute
  AuthenticatedHabitsHabitIdRoute: typeof AuthenticatedHabitsHabitIdRouteWithChildren
  AuthenticatedHabitsNewRoute: typeof AuthenticatedHabitsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedForestRoute: AuthenticatedForestRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedYouRoute: AuthenticatedYouRoute,
  AuthenticatedHabitsHabitIdRoute: AuthenticatedHabitsHabitIdRouteWithChildren,
  AuthenticatedHabitsNewRoute: AuthenticatedHabitsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
